stages:
  - build
  - test
  - deploy

default:
  tags:
    - docker

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
- apk update
- apk add ruby
- cd reddit
- gem install bundler -v 1.16.1
- bundle install

build_job:
  stage: build
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  script:
    - echo 'Testing 1'

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_job:
  stage: deploy
  script:
    - echo 'Deploy'
