---

- name: Install ruby, and needed dep's
  become: true
  apt:
    update-cache: true
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - ruby-full
    - ruby-bundler
    - build-essential
  tags: ruby
